/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2cpu' in SOPC Builder design 'NiosSoc'
 * SOPC Builder design path: C:/Users/USER/Desktop/DE2_70_NiosIISOC_final_version/Qsys/NiosSoc.sopcinfo
 *
 * Generated: Fri Dec 06 16:57:48 CST 2024
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_qsys"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x800820
#define ALT_CPU_CPU_FREQ 150000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "tiny"
#define ALT_CPU_DATA_ADDR_WIDTH 0x1c
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x8000020
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 150000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 0
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 0
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_ICACHE_SIZE 0
#define ALT_CPU_INST_ADDR_WIDTH 0x1c
#define ALT_CPU_NAME "nios2cpu"
#define ALT_CPU_RESET_ADDR 0x0


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x800820
#define NIOS2_CPU_FREQ 150000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "tiny"
#define NIOS2_DATA_ADDR_WIDTH 0x1c
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x8000020
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 0
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 0
#define NIOS2_ICACHE_LINE_SIZE_LOG2 0
#define NIOS2_ICACHE_SIZE 0
#define NIOS2_INST_ADDR_WIDTH 0x1c
#define NIOS2_RESET_ADDR 0x0


/*
 * Custom instruction macros
 *
 */

#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_0(n,A,B) __builtin_custom_inii(ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_0_N+(n&ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_0_N_MASK),(A),(B))
#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_0_N 0xfc
#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_0_N_MASK ((1<<2)-1)


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_DMA
#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_NEW_SDRAM_CONTROLLER
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_TIMER
#define __ALTERA_AVALON_UART
#define __ALTERA_GENERIC_TRISTATE_CONTROLLER
#define __ALTERA_NIOS2_QSYS
#define __ALTERA_NIOS_CUSTOM_INSTR_FLOATING_POINT
#define __ALTPLL
#define __LTM_MM


/*
 * SEG0 configuration
 *
 */

#define ALT_MODULE_CLASS_SEG0 altera_avalon_pio
#define SEG0_BASE 0x20000b0
#define SEG0_BIT_CLEARING_EDGE_REGISTER 0
#define SEG0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SEG0_CAPTURE 0
#define SEG0_DATA_WIDTH 8
#define SEG0_DO_TEST_BENCH_WIRING 0
#define SEG0_DRIVEN_SIM_VALUE 0
#define SEG0_EDGE_TYPE "NONE"
#define SEG0_FREQ 10000000
#define SEG0_HAS_IN 0
#define SEG0_HAS_OUT 1
#define SEG0_HAS_TRI 0
#define SEG0_IRQ -1
#define SEG0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SEG0_IRQ_TYPE "NONE"
#define SEG0_NAME "/dev/SEG0"
#define SEG0_RESET_VALUE 0
#define SEG0_SPAN 16
#define SEG0_TYPE "altera_avalon_pio"


/*
 * SEG0 configuration as viewed by dma_read_master
 *
 */

#define DMA_READ_MASTER_SEG0_BASE 0x20000b0
#define DMA_READ_MASTER_SEG0_BIT_CLEARING_EDGE_REGISTER 0
#define DMA_READ_MASTER_SEG0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DMA_READ_MASTER_SEG0_CAPTURE 0
#define DMA_READ_MASTER_SEG0_DATA_WIDTH 8
#define DMA_READ_MASTER_SEG0_DO_TEST_BENCH_WIRING 0
#define DMA_READ_MASTER_SEG0_DRIVEN_SIM_VALUE 0
#define DMA_READ_MASTER_SEG0_EDGE_TYPE "NONE"
#define DMA_READ_MASTER_SEG0_FREQ 10000000
#define DMA_READ_MASTER_SEG0_HAS_IN 0
#define DMA_READ_MASTER_SEG0_HAS_OUT 1
#define DMA_READ_MASTER_SEG0_HAS_TRI 0
#define DMA_READ_MASTER_SEG0_IRQ -1
#define DMA_READ_MASTER_SEG0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_READ_MASTER_SEG0_IRQ_TYPE "NONE"
#define DMA_READ_MASTER_SEG0_NAME "/dev/SEG0"
#define DMA_READ_MASTER_SEG0_RESET_VALUE 0
#define DMA_READ_MASTER_SEG0_SPAN 16
#define DMA_READ_MASTER_SEG0_TYPE "altera_avalon_pio"


/*
 * SEG0 configuration as viewed by dma_write_master
 *
 */

#define DMA_WRITE_MASTER_SEG0_BASE 0x20000b0
#define DMA_WRITE_MASTER_SEG0_BIT_CLEARING_EDGE_REGISTER 0
#define DMA_WRITE_MASTER_SEG0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DMA_WRITE_MASTER_SEG0_CAPTURE 0
#define DMA_WRITE_MASTER_SEG0_DATA_WIDTH 8
#define DMA_WRITE_MASTER_SEG0_DO_TEST_BENCH_WIRING 0
#define DMA_WRITE_MASTER_SEG0_DRIVEN_SIM_VALUE 0
#define DMA_WRITE_MASTER_SEG0_EDGE_TYPE "NONE"
#define DMA_WRITE_MASTER_SEG0_FREQ 10000000
#define DMA_WRITE_MASTER_SEG0_HAS_IN 0
#define DMA_WRITE_MASTER_SEG0_HAS_OUT 1
#define DMA_WRITE_MASTER_SEG0_HAS_TRI 0
#define DMA_WRITE_MASTER_SEG0_IRQ -1
#define DMA_WRITE_MASTER_SEG0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_WRITE_MASTER_SEG0_IRQ_TYPE "NONE"
#define DMA_WRITE_MASTER_SEG0_NAME "/dev/SEG0"
#define DMA_WRITE_MASTER_SEG0_RESET_VALUE 0
#define DMA_WRITE_MASTER_SEG0_SPAN 16
#define DMA_WRITE_MASTER_SEG0_TYPE "altera_avalon_pio"


/*
 * SEG1 configuration
 *
 */

#define ALT_MODULE_CLASS_SEG1 altera_avalon_pio
#define SEG1_BASE 0x20000a0
#define SEG1_BIT_CLEARING_EDGE_REGISTER 0
#define SEG1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SEG1_CAPTURE 0
#define SEG1_DATA_WIDTH 8
#define SEG1_DO_TEST_BENCH_WIRING 0
#define SEG1_DRIVEN_SIM_VALUE 0
#define SEG1_EDGE_TYPE "NONE"
#define SEG1_FREQ 10000000
#define SEG1_HAS_IN 0
#define SEG1_HAS_OUT 1
#define SEG1_HAS_TRI 0
#define SEG1_IRQ -1
#define SEG1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SEG1_IRQ_TYPE "NONE"
#define SEG1_NAME "/dev/SEG1"
#define SEG1_RESET_VALUE 0
#define SEG1_SPAN 16
#define SEG1_TYPE "altera_avalon_pio"


/*
 * SEG1 configuration as viewed by dma_read_master
 *
 */

#define DMA_READ_MASTER_SEG1_BASE 0x20000a0
#define DMA_READ_MASTER_SEG1_BIT_CLEARING_EDGE_REGISTER 0
#define DMA_READ_MASTER_SEG1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DMA_READ_MASTER_SEG1_CAPTURE 0
#define DMA_READ_MASTER_SEG1_DATA_WIDTH 8
#define DMA_READ_MASTER_SEG1_DO_TEST_BENCH_WIRING 0
#define DMA_READ_MASTER_SEG1_DRIVEN_SIM_VALUE 0
#define DMA_READ_MASTER_SEG1_EDGE_TYPE "NONE"
#define DMA_READ_MASTER_SEG1_FREQ 10000000
#define DMA_READ_MASTER_SEG1_HAS_IN 0
#define DMA_READ_MASTER_SEG1_HAS_OUT 1
#define DMA_READ_MASTER_SEG1_HAS_TRI 0
#define DMA_READ_MASTER_SEG1_IRQ -1
#define DMA_READ_MASTER_SEG1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_READ_MASTER_SEG1_IRQ_TYPE "NONE"
#define DMA_READ_MASTER_SEG1_NAME "/dev/SEG1"
#define DMA_READ_MASTER_SEG1_RESET_VALUE 0
#define DMA_READ_MASTER_SEG1_SPAN 16
#define DMA_READ_MASTER_SEG1_TYPE "altera_avalon_pio"


/*
 * SEG1 configuration as viewed by dma_write_master
 *
 */

#define DMA_WRITE_MASTER_SEG1_BASE 0x20000a0
#define DMA_WRITE_MASTER_SEG1_BIT_CLEARING_EDGE_REGISTER 0
#define DMA_WRITE_MASTER_SEG1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DMA_WRITE_MASTER_SEG1_CAPTURE 0
#define DMA_WRITE_MASTER_SEG1_DATA_WIDTH 8
#define DMA_WRITE_MASTER_SEG1_DO_TEST_BENCH_WIRING 0
#define DMA_WRITE_MASTER_SEG1_DRIVEN_SIM_VALUE 0
#define DMA_WRITE_MASTER_SEG1_EDGE_TYPE "NONE"
#define DMA_WRITE_MASTER_SEG1_FREQ 10000000
#define DMA_WRITE_MASTER_SEG1_HAS_IN 0
#define DMA_WRITE_MASTER_SEG1_HAS_OUT 1
#define DMA_WRITE_MASTER_SEG1_HAS_TRI 0
#define DMA_WRITE_MASTER_SEG1_IRQ -1
#define DMA_WRITE_MASTER_SEG1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_WRITE_MASTER_SEG1_IRQ_TYPE "NONE"
#define DMA_WRITE_MASTER_SEG1_NAME "/dev/SEG1"
#define DMA_WRITE_MASTER_SEG1_RESET_VALUE 0
#define DMA_WRITE_MASTER_SEG1_SPAN 16
#define DMA_WRITE_MASTER_SEG1_TYPE "altera_avalon_pio"


/*
 * SEG2 configuration
 *
 */

#define ALT_MODULE_CLASS_SEG2 altera_avalon_pio
#define SEG2_BASE 0x2000090
#define SEG2_BIT_CLEARING_EDGE_REGISTER 0
#define SEG2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SEG2_CAPTURE 0
#define SEG2_DATA_WIDTH 8
#define SEG2_DO_TEST_BENCH_WIRING 0
#define SEG2_DRIVEN_SIM_VALUE 0
#define SEG2_EDGE_TYPE "NONE"
#define SEG2_FREQ 10000000
#define SEG2_HAS_IN 0
#define SEG2_HAS_OUT 1
#define SEG2_HAS_TRI 0
#define SEG2_IRQ -1
#define SEG2_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SEG2_IRQ_TYPE "NONE"
#define SEG2_NAME "/dev/SEG2"
#define SEG2_RESET_VALUE 0
#define SEG2_SPAN 16
#define SEG2_TYPE "altera_avalon_pio"


/*
 * SEG2 configuration as viewed by dma_read_master
 *
 */

#define DMA_READ_MASTER_SEG2_BASE 0x2000090
#define DMA_READ_MASTER_SEG2_BIT_CLEARING_EDGE_REGISTER 0
#define DMA_READ_MASTER_SEG2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DMA_READ_MASTER_SEG2_CAPTURE 0
#define DMA_READ_MASTER_SEG2_DATA_WIDTH 8
#define DMA_READ_MASTER_SEG2_DO_TEST_BENCH_WIRING 0
#define DMA_READ_MASTER_SEG2_DRIVEN_SIM_VALUE 0
#define DMA_READ_MASTER_SEG2_EDGE_TYPE "NONE"
#define DMA_READ_MASTER_SEG2_FREQ 10000000
#define DMA_READ_MASTER_SEG2_HAS_IN 0
#define DMA_READ_MASTER_SEG2_HAS_OUT 1
#define DMA_READ_MASTER_SEG2_HAS_TRI 0
#define DMA_READ_MASTER_SEG2_IRQ -1
#define DMA_READ_MASTER_SEG2_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_READ_MASTER_SEG2_IRQ_TYPE "NONE"
#define DMA_READ_MASTER_SEG2_NAME "/dev/SEG2"
#define DMA_READ_MASTER_SEG2_RESET_VALUE 0
#define DMA_READ_MASTER_SEG2_SPAN 16
#define DMA_READ_MASTER_SEG2_TYPE "altera_avalon_pio"


/*
 * SEG2 configuration as viewed by dma_write_master
 *
 */

#define DMA_WRITE_MASTER_SEG2_BASE 0x2000090
#define DMA_WRITE_MASTER_SEG2_BIT_CLEARING_EDGE_REGISTER 0
#define DMA_WRITE_MASTER_SEG2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DMA_WRITE_MASTER_SEG2_CAPTURE 0
#define DMA_WRITE_MASTER_SEG2_DATA_WIDTH 8
#define DMA_WRITE_MASTER_SEG2_DO_TEST_BENCH_WIRING 0
#define DMA_WRITE_MASTER_SEG2_DRIVEN_SIM_VALUE 0
#define DMA_WRITE_MASTER_SEG2_EDGE_TYPE "NONE"
#define DMA_WRITE_MASTER_SEG2_FREQ 10000000
#define DMA_WRITE_MASTER_SEG2_HAS_IN 0
#define DMA_WRITE_MASTER_SEG2_HAS_OUT 1
#define DMA_WRITE_MASTER_SEG2_HAS_TRI 0
#define DMA_WRITE_MASTER_SEG2_IRQ -1
#define DMA_WRITE_MASTER_SEG2_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_WRITE_MASTER_SEG2_IRQ_TYPE "NONE"
#define DMA_WRITE_MASTER_SEG2_NAME "/dev/SEG2"
#define DMA_WRITE_MASTER_SEG2_RESET_VALUE 0
#define DMA_WRITE_MASTER_SEG2_SPAN 16
#define DMA_WRITE_MASTER_SEG2_TYPE "altera_avalon_pio"


/*
 * SEG3 configuration
 *
 */

#define ALT_MODULE_CLASS_SEG3 altera_avalon_pio
#define SEG3_BASE 0x2000080
#define SEG3_BIT_CLEARING_EDGE_REGISTER 0
#define SEG3_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SEG3_CAPTURE 0
#define SEG3_DATA_WIDTH 8
#define SEG3_DO_TEST_BENCH_WIRING 0
#define SEG3_DRIVEN_SIM_VALUE 0
#define SEG3_EDGE_TYPE "NONE"
#define SEG3_FREQ 10000000
#define SEG3_HAS_IN 0
#define SEG3_HAS_OUT 1
#define SEG3_HAS_TRI 0
#define SEG3_IRQ -1
#define SEG3_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SEG3_IRQ_TYPE "NONE"
#define SEG3_NAME "/dev/SEG3"
#define SEG3_RESET_VALUE 0
#define SEG3_SPAN 16
#define SEG3_TYPE "altera_avalon_pio"


/*
 * SEG3 configuration as viewed by dma_read_master
 *
 */

#define DMA_READ_MASTER_SEG3_BASE 0x2000080
#define DMA_READ_MASTER_SEG3_BIT_CLEARING_EDGE_REGISTER 0
#define DMA_READ_MASTER_SEG3_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DMA_READ_MASTER_SEG3_CAPTURE 0
#define DMA_READ_MASTER_SEG3_DATA_WIDTH 8
#define DMA_READ_MASTER_SEG3_DO_TEST_BENCH_WIRING 0
#define DMA_READ_MASTER_SEG3_DRIVEN_SIM_VALUE 0
#define DMA_READ_MASTER_SEG3_EDGE_TYPE "NONE"
#define DMA_READ_MASTER_SEG3_FREQ 10000000
#define DMA_READ_MASTER_SEG3_HAS_IN 0
#define DMA_READ_MASTER_SEG3_HAS_OUT 1
#define DMA_READ_MASTER_SEG3_HAS_TRI 0
#define DMA_READ_MASTER_SEG3_IRQ -1
#define DMA_READ_MASTER_SEG3_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_READ_MASTER_SEG3_IRQ_TYPE "NONE"
#define DMA_READ_MASTER_SEG3_NAME "/dev/SEG3"
#define DMA_READ_MASTER_SEG3_RESET_VALUE 0
#define DMA_READ_MASTER_SEG3_SPAN 16
#define DMA_READ_MASTER_SEG3_TYPE "altera_avalon_pio"


/*
 * SEG3 configuration as viewed by dma_write_master
 *
 */

#define DMA_WRITE_MASTER_SEG3_BASE 0x2000080
#define DMA_WRITE_MASTER_SEG3_BIT_CLEARING_EDGE_REGISTER 0
#define DMA_WRITE_MASTER_SEG3_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DMA_WRITE_MASTER_SEG3_CAPTURE 0
#define DMA_WRITE_MASTER_SEG3_DATA_WIDTH 8
#define DMA_WRITE_MASTER_SEG3_DO_TEST_BENCH_WIRING 0
#define DMA_WRITE_MASTER_SEG3_DRIVEN_SIM_VALUE 0
#define DMA_WRITE_MASTER_SEG3_EDGE_TYPE "NONE"
#define DMA_WRITE_MASTER_SEG3_FREQ 10000000
#define DMA_WRITE_MASTER_SEG3_HAS_IN 0
#define DMA_WRITE_MASTER_SEG3_HAS_OUT 1
#define DMA_WRITE_MASTER_SEG3_HAS_TRI 0
#define DMA_WRITE_MASTER_SEG3_IRQ -1
#define DMA_WRITE_MASTER_SEG3_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_WRITE_MASTER_SEG3_IRQ_TYPE "NONE"
#define DMA_WRITE_MASTER_SEG3_NAME "/dev/SEG3"
#define DMA_WRITE_MASTER_SEG3_RESET_VALUE 0
#define DMA_WRITE_MASTER_SEG3_SPAN 16
#define DMA_WRITE_MASTER_SEG3_TYPE "altera_avalon_pio"


/*
 * SEG4 configuration
 *
 */

#define ALT_MODULE_CLASS_SEG4 altera_avalon_pio
#define SEG4_BASE 0x2000070
#define SEG4_BIT_CLEARING_EDGE_REGISTER 0
#define SEG4_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SEG4_CAPTURE 0
#define SEG4_DATA_WIDTH 8
#define SEG4_DO_TEST_BENCH_WIRING 0
#define SEG4_DRIVEN_SIM_VALUE 0
#define SEG4_EDGE_TYPE "NONE"
#define SEG4_FREQ 10000000
#define SEG4_HAS_IN 0
#define SEG4_HAS_OUT 1
#define SEG4_HAS_TRI 0
#define SEG4_IRQ -1
#define SEG4_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SEG4_IRQ_TYPE "NONE"
#define SEG4_NAME "/dev/SEG4"
#define SEG4_RESET_VALUE 0
#define SEG4_SPAN 16
#define SEG4_TYPE "altera_avalon_pio"


/*
 * SEG4 configuration as viewed by dma_read_master
 *
 */

#define DMA_READ_MASTER_SEG4_BASE 0x2000070
#define DMA_READ_MASTER_SEG4_BIT_CLEARING_EDGE_REGISTER 0
#define DMA_READ_MASTER_SEG4_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DMA_READ_MASTER_SEG4_CAPTURE 0
#define DMA_READ_MASTER_SEG4_DATA_WIDTH 8
#define DMA_READ_MASTER_SEG4_DO_TEST_BENCH_WIRING 0
#define DMA_READ_MASTER_SEG4_DRIVEN_SIM_VALUE 0
#define DMA_READ_MASTER_SEG4_EDGE_TYPE "NONE"
#define DMA_READ_MASTER_SEG4_FREQ 10000000
#define DMA_READ_MASTER_SEG4_HAS_IN 0
#define DMA_READ_MASTER_SEG4_HAS_OUT 1
#define DMA_READ_MASTER_SEG4_HAS_TRI 0
#define DMA_READ_MASTER_SEG4_IRQ -1
#define DMA_READ_MASTER_SEG4_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_READ_MASTER_SEG4_IRQ_TYPE "NONE"
#define DMA_READ_MASTER_SEG4_NAME "/dev/SEG4"
#define DMA_READ_MASTER_SEG4_RESET_VALUE 0
#define DMA_READ_MASTER_SEG4_SPAN 16
#define DMA_READ_MASTER_SEG4_TYPE "altera_avalon_pio"


/*
 * SEG4 configuration as viewed by dma_write_master
 *
 */

#define DMA_WRITE_MASTER_SEG4_BASE 0x2000070
#define DMA_WRITE_MASTER_SEG4_BIT_CLEARING_EDGE_REGISTER 0
#define DMA_WRITE_MASTER_SEG4_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DMA_WRITE_MASTER_SEG4_CAPTURE 0
#define DMA_WRITE_MASTER_SEG4_DATA_WIDTH 8
#define DMA_WRITE_MASTER_SEG4_DO_TEST_BENCH_WIRING 0
#define DMA_WRITE_MASTER_SEG4_DRIVEN_SIM_VALUE 0
#define DMA_WRITE_MASTER_SEG4_EDGE_TYPE "NONE"
#define DMA_WRITE_MASTER_SEG4_FREQ 10000000
#define DMA_WRITE_MASTER_SEG4_HAS_IN 0
#define DMA_WRITE_MASTER_SEG4_HAS_OUT 1
#define DMA_WRITE_MASTER_SEG4_HAS_TRI 0
#define DMA_WRITE_MASTER_SEG4_IRQ -1
#define DMA_WRITE_MASTER_SEG4_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_WRITE_MASTER_SEG4_IRQ_TYPE "NONE"
#define DMA_WRITE_MASTER_SEG4_NAME "/dev/SEG4"
#define DMA_WRITE_MASTER_SEG4_RESET_VALUE 0
#define DMA_WRITE_MASTER_SEG4_SPAN 16
#define DMA_WRITE_MASTER_SEG4_TYPE "altera_avalon_pio"


/*
 * SEG5 configuration
 *
 */

#define ALT_MODULE_CLASS_SEG5 altera_avalon_pio
#define SEG5_BASE 0x2000060
#define SEG5_BIT_CLEARING_EDGE_REGISTER 0
#define SEG5_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SEG5_CAPTURE 0
#define SEG5_DATA_WIDTH 8
#define SEG5_DO_TEST_BENCH_WIRING 0
#define SEG5_DRIVEN_SIM_VALUE 0
#define SEG5_EDGE_TYPE "NONE"
#define SEG5_FREQ 10000000
#define SEG5_HAS_IN 0
#define SEG5_HAS_OUT 1
#define SEG5_HAS_TRI 0
#define SEG5_IRQ -1
#define SEG5_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SEG5_IRQ_TYPE "NONE"
#define SEG5_NAME "/dev/SEG5"
#define SEG5_RESET_VALUE 0
#define SEG5_SPAN 16
#define SEG5_TYPE "altera_avalon_pio"


/*
 * SEG5 configuration as viewed by dma_read_master
 *
 */

#define DMA_READ_MASTER_SEG5_BASE 0x2000060
#define DMA_READ_MASTER_SEG5_BIT_CLEARING_EDGE_REGISTER 0
#define DMA_READ_MASTER_SEG5_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DMA_READ_MASTER_SEG5_CAPTURE 0
#define DMA_READ_MASTER_SEG5_DATA_WIDTH 8
#define DMA_READ_MASTER_SEG5_DO_TEST_BENCH_WIRING 0
#define DMA_READ_MASTER_SEG5_DRIVEN_SIM_VALUE 0
#define DMA_READ_MASTER_SEG5_EDGE_TYPE "NONE"
#define DMA_READ_MASTER_SEG5_FREQ 10000000
#define DMA_READ_MASTER_SEG5_HAS_IN 0
#define DMA_READ_MASTER_SEG5_HAS_OUT 1
#define DMA_READ_MASTER_SEG5_HAS_TRI 0
#define DMA_READ_MASTER_SEG5_IRQ -1
#define DMA_READ_MASTER_SEG5_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_READ_MASTER_SEG5_IRQ_TYPE "NONE"
#define DMA_READ_MASTER_SEG5_NAME "/dev/SEG5"
#define DMA_READ_MASTER_SEG5_RESET_VALUE 0
#define DMA_READ_MASTER_SEG5_SPAN 16
#define DMA_READ_MASTER_SEG5_TYPE "altera_avalon_pio"


/*
 * SEG5 configuration as viewed by dma_write_master
 *
 */

#define DMA_WRITE_MASTER_SEG5_BASE 0x2000060
#define DMA_WRITE_MASTER_SEG5_BIT_CLEARING_EDGE_REGISTER 0
#define DMA_WRITE_MASTER_SEG5_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DMA_WRITE_MASTER_SEG5_CAPTURE 0
#define DMA_WRITE_MASTER_SEG5_DATA_WIDTH 8
#define DMA_WRITE_MASTER_SEG5_DO_TEST_BENCH_WIRING 0
#define DMA_WRITE_MASTER_SEG5_DRIVEN_SIM_VALUE 0
#define DMA_WRITE_MASTER_SEG5_EDGE_TYPE "NONE"
#define DMA_WRITE_MASTER_SEG5_FREQ 10000000
#define DMA_WRITE_MASTER_SEG5_HAS_IN 0
#define DMA_WRITE_MASTER_SEG5_HAS_OUT 1
#define DMA_WRITE_MASTER_SEG5_HAS_TRI 0
#define DMA_WRITE_MASTER_SEG5_IRQ -1
#define DMA_WRITE_MASTER_SEG5_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_WRITE_MASTER_SEG5_IRQ_TYPE "NONE"
#define DMA_WRITE_MASTER_SEG5_NAME "/dev/SEG5"
#define DMA_WRITE_MASTER_SEG5_RESET_VALUE 0
#define DMA_WRITE_MASTER_SEG5_SPAN 16
#define DMA_WRITE_MASTER_SEG5_TYPE "altera_avalon_pio"


/*
 * SEG6 configuration
 *
 */

#define ALT_MODULE_CLASS_SEG6 altera_avalon_pio
#define SEG6_BASE 0x2000050
#define SEG6_BIT_CLEARING_EDGE_REGISTER 0
#define SEG6_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SEG6_CAPTURE 0
#define SEG6_DATA_WIDTH 8
#define SEG6_DO_TEST_BENCH_WIRING 0
#define SEG6_DRIVEN_SIM_VALUE 0
#define SEG6_EDGE_TYPE "NONE"
#define SEG6_FREQ 10000000
#define SEG6_HAS_IN 0
#define SEG6_HAS_OUT 1
#define SEG6_HAS_TRI 0
#define SEG6_IRQ -1
#define SEG6_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SEG6_IRQ_TYPE "NONE"
#define SEG6_NAME "/dev/SEG6"
#define SEG6_RESET_VALUE 0
#define SEG6_SPAN 16
#define SEG6_TYPE "altera_avalon_pio"


/*
 * SEG6 configuration as viewed by dma_read_master
 *
 */

#define DMA_READ_MASTER_SEG6_BASE 0x2000050
#define DMA_READ_MASTER_SEG6_BIT_CLEARING_EDGE_REGISTER 0
#define DMA_READ_MASTER_SEG6_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DMA_READ_MASTER_SEG6_CAPTURE 0
#define DMA_READ_MASTER_SEG6_DATA_WIDTH 8
#define DMA_READ_MASTER_SEG6_DO_TEST_BENCH_WIRING 0
#define DMA_READ_MASTER_SEG6_DRIVEN_SIM_VALUE 0
#define DMA_READ_MASTER_SEG6_EDGE_TYPE "NONE"
#define DMA_READ_MASTER_SEG6_FREQ 10000000
#define DMA_READ_MASTER_SEG6_HAS_IN 0
#define DMA_READ_MASTER_SEG6_HAS_OUT 1
#define DMA_READ_MASTER_SEG6_HAS_TRI 0
#define DMA_READ_MASTER_SEG6_IRQ -1
#define DMA_READ_MASTER_SEG6_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_READ_MASTER_SEG6_IRQ_TYPE "NONE"
#define DMA_READ_MASTER_SEG6_NAME "/dev/SEG6"
#define DMA_READ_MASTER_SEG6_RESET_VALUE 0
#define DMA_READ_MASTER_SEG6_SPAN 16
#define DMA_READ_MASTER_SEG6_TYPE "altera_avalon_pio"


/*
 * SEG6 configuration as viewed by dma_write_master
 *
 */

#define DMA_WRITE_MASTER_SEG6_BASE 0x2000050
#define DMA_WRITE_MASTER_SEG6_BIT_CLEARING_EDGE_REGISTER 0
#define DMA_WRITE_MASTER_SEG6_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DMA_WRITE_MASTER_SEG6_CAPTURE 0
#define DMA_WRITE_MASTER_SEG6_DATA_WIDTH 8
#define DMA_WRITE_MASTER_SEG6_DO_TEST_BENCH_WIRING 0
#define DMA_WRITE_MASTER_SEG6_DRIVEN_SIM_VALUE 0
#define DMA_WRITE_MASTER_SEG6_EDGE_TYPE "NONE"
#define DMA_WRITE_MASTER_SEG6_FREQ 10000000
#define DMA_WRITE_MASTER_SEG6_HAS_IN 0
#define DMA_WRITE_MASTER_SEG6_HAS_OUT 1
#define DMA_WRITE_MASTER_SEG6_HAS_TRI 0
#define DMA_WRITE_MASTER_SEG6_IRQ -1
#define DMA_WRITE_MASTER_SEG6_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_WRITE_MASTER_SEG6_IRQ_TYPE "NONE"
#define DMA_WRITE_MASTER_SEG6_NAME "/dev/SEG6"
#define DMA_WRITE_MASTER_SEG6_RESET_VALUE 0
#define DMA_WRITE_MASTER_SEG6_SPAN 16
#define DMA_WRITE_MASTER_SEG6_TYPE "altera_avalon_pio"


/*
 * SEG7 configuration
 *
 */

#define ALT_MODULE_CLASS_SEG7 altera_avalon_pio
#define SEG7_BASE 0x2000040
#define SEG7_BIT_CLEARING_EDGE_REGISTER 0
#define SEG7_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SEG7_CAPTURE 0
#define SEG7_DATA_WIDTH 8
#define SEG7_DO_TEST_BENCH_WIRING 0
#define SEG7_DRIVEN_SIM_VALUE 0
#define SEG7_EDGE_TYPE "NONE"
#define SEG7_FREQ 10000000
#define SEG7_HAS_IN 0
#define SEG7_HAS_OUT 1
#define SEG7_HAS_TRI 0
#define SEG7_IRQ -1
#define SEG7_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SEG7_IRQ_TYPE "NONE"
#define SEG7_NAME "/dev/SEG7"
#define SEG7_RESET_VALUE 0
#define SEG7_SPAN 16
#define SEG7_TYPE "altera_avalon_pio"


/*
 * SEG7 configuration as viewed by dma_read_master
 *
 */

#define DMA_READ_MASTER_SEG7_BASE 0x2000040
#define DMA_READ_MASTER_SEG7_BIT_CLEARING_EDGE_REGISTER 0
#define DMA_READ_MASTER_SEG7_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DMA_READ_MASTER_SEG7_CAPTURE 0
#define DMA_READ_MASTER_SEG7_DATA_WIDTH 8
#define DMA_READ_MASTER_SEG7_DO_TEST_BENCH_WIRING 0
#define DMA_READ_MASTER_SEG7_DRIVEN_SIM_VALUE 0
#define DMA_READ_MASTER_SEG7_EDGE_TYPE "NONE"
#define DMA_READ_MASTER_SEG7_FREQ 10000000
#define DMA_READ_MASTER_SEG7_HAS_IN 0
#define DMA_READ_MASTER_SEG7_HAS_OUT 1
#define DMA_READ_MASTER_SEG7_HAS_TRI 0
#define DMA_READ_MASTER_SEG7_IRQ -1
#define DMA_READ_MASTER_SEG7_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_READ_MASTER_SEG7_IRQ_TYPE "NONE"
#define DMA_READ_MASTER_SEG7_NAME "/dev/SEG7"
#define DMA_READ_MASTER_SEG7_RESET_VALUE 0
#define DMA_READ_MASTER_SEG7_SPAN 16
#define DMA_READ_MASTER_SEG7_TYPE "altera_avalon_pio"


/*
 * SEG7 configuration as viewed by dma_write_master
 *
 */

#define DMA_WRITE_MASTER_SEG7_BASE 0x2000040
#define DMA_WRITE_MASTER_SEG7_BIT_CLEARING_EDGE_REGISTER 0
#define DMA_WRITE_MASTER_SEG7_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DMA_WRITE_MASTER_SEG7_CAPTURE 0
#define DMA_WRITE_MASTER_SEG7_DATA_WIDTH 8
#define DMA_WRITE_MASTER_SEG7_DO_TEST_BENCH_WIRING 0
#define DMA_WRITE_MASTER_SEG7_DRIVEN_SIM_VALUE 0
#define DMA_WRITE_MASTER_SEG7_EDGE_TYPE "NONE"
#define DMA_WRITE_MASTER_SEG7_FREQ 10000000
#define DMA_WRITE_MASTER_SEG7_HAS_IN 0
#define DMA_WRITE_MASTER_SEG7_HAS_OUT 1
#define DMA_WRITE_MASTER_SEG7_HAS_TRI 0
#define DMA_WRITE_MASTER_SEG7_IRQ -1
#define DMA_WRITE_MASTER_SEG7_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_WRITE_MASTER_SEG7_IRQ_TYPE "NONE"
#define DMA_WRITE_MASTER_SEG7_NAME "/dev/SEG7"
#define DMA_WRITE_MASTER_SEG7_RESET_VALUE 0
#define DMA_WRITE_MASTER_SEG7_SPAN 16
#define DMA_WRITE_MASTER_SEG7_TYPE "altera_avalon_pio"


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone II"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart"
#define ALT_STDERR_BASE 0x20000e0
#define ALT_STDERR_DEV jtag_uart
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart"
#define ALT_STDIN_BASE 0x20000e0
#define ALT_STDIN_DEV jtag_uart
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart"
#define ALT_STDOUT_BASE 0x20000e0
#define ALT_STDOUT_DEV jtag_uart
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "NiosSoc"


/*
 * altera_ro_zipfs configuration
 *
 */

#define ALTERA_RO_ZIPFS_BASE 0x0
#define ALTERA_RO_ZIPFS_NAME "/mnt/rozipfs"
#define ALTERA_RO_ZIPFS_OFFSET 0x100000


/*
 * button configuration
 *
 */

#define ALT_MODULE_CLASS_button altera_avalon_pio
#define BUTTON_BASE 0x20000c0
#define BUTTON_BIT_CLEARING_EDGE_REGISTER 0
#define BUTTON_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BUTTON_CAPTURE 1
#define BUTTON_DATA_WIDTH 4
#define BUTTON_DO_TEST_BENCH_WIRING 0
#define BUTTON_DRIVEN_SIM_VALUE 0
#define BUTTON_EDGE_TYPE "FALLING"
#define BUTTON_FREQ 10000000
#define BUTTON_HAS_IN 1
#define BUTTON_HAS_OUT 0
#define BUTTON_HAS_TRI 0
#define BUTTON_IRQ 5
#define BUTTON_IRQ_INTERRUPT_CONTROLLER_ID 0
#define BUTTON_IRQ_TYPE "EDGE"
#define BUTTON_NAME "/dev/button"
#define BUTTON_RESET_VALUE 0
#define BUTTON_SPAN 16
#define BUTTON_TYPE "altera_avalon_pio"


/*
 * button configuration as viewed by dma_read_master
 *
 */

#define DMA_READ_MASTER_BUTTON_BASE 0x20000c0
#define DMA_READ_MASTER_BUTTON_BIT_CLEARING_EDGE_REGISTER 0
#define DMA_READ_MASTER_BUTTON_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DMA_READ_MASTER_BUTTON_CAPTURE 1
#define DMA_READ_MASTER_BUTTON_DATA_WIDTH 4
#define DMA_READ_MASTER_BUTTON_DO_TEST_BENCH_WIRING 0
#define DMA_READ_MASTER_BUTTON_DRIVEN_SIM_VALUE 0
#define DMA_READ_MASTER_BUTTON_EDGE_TYPE "FALLING"
#define DMA_READ_MASTER_BUTTON_FREQ 10000000
#define DMA_READ_MASTER_BUTTON_HAS_IN 1
#define DMA_READ_MASTER_BUTTON_HAS_OUT 0
#define DMA_READ_MASTER_BUTTON_HAS_TRI 0
#define DMA_READ_MASTER_BUTTON_IRQ -1
#define DMA_READ_MASTER_BUTTON_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_READ_MASTER_BUTTON_IRQ_TYPE "EDGE"
#define DMA_READ_MASTER_BUTTON_NAME "/dev/button"
#define DMA_READ_MASTER_BUTTON_RESET_VALUE 0
#define DMA_READ_MASTER_BUTTON_SPAN 16
#define DMA_READ_MASTER_BUTTON_TYPE "altera_avalon_pio"


/*
 * button configuration as viewed by dma_write_master
 *
 */

#define DMA_WRITE_MASTER_BUTTON_BASE 0x20000c0
#define DMA_WRITE_MASTER_BUTTON_BIT_CLEARING_EDGE_REGISTER 0
#define DMA_WRITE_MASTER_BUTTON_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DMA_WRITE_MASTER_BUTTON_CAPTURE 1
#define DMA_WRITE_MASTER_BUTTON_DATA_WIDTH 4
#define DMA_WRITE_MASTER_BUTTON_DO_TEST_BENCH_WIRING 0
#define DMA_WRITE_MASTER_BUTTON_DRIVEN_SIM_VALUE 0
#define DMA_WRITE_MASTER_BUTTON_EDGE_TYPE "FALLING"
#define DMA_WRITE_MASTER_BUTTON_FREQ 10000000
#define DMA_WRITE_MASTER_BUTTON_HAS_IN 1
#define DMA_WRITE_MASTER_BUTTON_HAS_OUT 0
#define DMA_WRITE_MASTER_BUTTON_HAS_TRI 0
#define DMA_WRITE_MASTER_BUTTON_IRQ -1
#define DMA_WRITE_MASTER_BUTTON_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_WRITE_MASTER_BUTTON_IRQ_TYPE "EDGE"
#define DMA_WRITE_MASTER_BUTTON_NAME "/dev/button"
#define DMA_WRITE_MASTER_BUTTON_RESET_VALUE 0
#define DMA_WRITE_MASTER_BUTTON_SPAN 16
#define DMA_WRITE_MASTER_BUTTON_TYPE "altera_avalon_pio"


/*
 * dma configuration
 *
 */

#define ALT_MODULE_CLASS_dma altera_avalon_dma
#define DMA_ALLOW_BYTE_TRANSACTIONS 1
#define DMA_ALLOW_DOUBLEWORD_TRANSACTIONS 1
#define DMA_ALLOW_HW_TRANSACTIONS 1
#define DMA_ALLOW_QUADWORD_TRANSACTIONS 1
#define DMA_ALLOW_WORD_TRANSACTIONS 1
#define DMA_BASE 0x801040
#define DMA_IRQ 3
#define DMA_IRQ_INTERRUPT_CONTROLLER_ID 0
#define DMA_LENGTHWIDTH 13
#define DMA_MAX_BURST_SIZE 128
#define DMA_NAME "/dev/dma"
#define DMA_SPAN 32
#define DMA_TYPE "altera_avalon_dma"


/*
 * ext_flash configuration
 *
 */

#define ALT_MODULE_CLASS_ext_flash altera_generic_tristate_controller
#define EXT_FLASH_BASE 0x0
#define EXT_FLASH_HOLD_VALUE 40
#define EXT_FLASH_IRQ -1
#define EXT_FLASH_IRQ_INTERRUPT_CONTROLLER_ID -1
#define EXT_FLASH_NAME "/dev/ext_flash"
#define EXT_FLASH_SETUP_VALUE 40
#define EXT_FLASH_SIZE 8388608u
#define EXT_FLASH_SPAN 8388608
#define EXT_FLASH_TIMING_UNITS "ns"
#define EXT_FLASH_TYPE "altera_generic_tristate_controller"
#define EXT_FLASH_WAIT_VALUE 160


/*
 * hal configuration
 *
 */

#define ALT_MAX_FD 32
#define ALT_SYS_CLK none
#define ALT_TIMESTAMP_CLK TIMER


/*
 * jtag_uart configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart altera_avalon_jtag_uart
#define JTAG_UART_BASE 0x20000e0
#define JTAG_UART_IRQ 0
#define JTAG_UART_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_NAME "/dev/jtag_uart"
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_SPAN 8
#define JTAG_UART_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


/*
 * jtag_uart configuration as viewed by dma_read_master
 *
 */

#define DMA_READ_MASTER_JTAG_UART_BASE 0x20000e0
#define DMA_READ_MASTER_JTAG_UART_IRQ -1
#define DMA_READ_MASTER_JTAG_UART_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_READ_MASTER_JTAG_UART_NAME "/dev/jtag_uart"
#define DMA_READ_MASTER_JTAG_UART_READ_DEPTH 64
#define DMA_READ_MASTER_JTAG_UART_READ_THRESHOLD 8
#define DMA_READ_MASTER_JTAG_UART_SPAN 8
#define DMA_READ_MASTER_JTAG_UART_TYPE "altera_avalon_jtag_uart"
#define DMA_READ_MASTER_JTAG_UART_WRITE_DEPTH 64
#define DMA_READ_MASTER_JTAG_UART_WRITE_THRESHOLD 8


/*
 * jtag_uart configuration as viewed by dma_write_master
 *
 */

#define DMA_WRITE_MASTER_JTAG_UART_BASE 0x20000e0
#define DMA_WRITE_MASTER_JTAG_UART_IRQ -1
#define DMA_WRITE_MASTER_JTAG_UART_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_WRITE_MASTER_JTAG_UART_NAME "/dev/jtag_uart"
#define DMA_WRITE_MASTER_JTAG_UART_READ_DEPTH 64
#define DMA_WRITE_MASTER_JTAG_UART_READ_THRESHOLD 8
#define DMA_WRITE_MASTER_JTAG_UART_SPAN 8
#define DMA_WRITE_MASTER_JTAG_UART_TYPE "altera_avalon_jtag_uart"
#define DMA_WRITE_MASTER_JTAG_UART_WRITE_DEPTH 64
#define DMA_WRITE_MASTER_JTAG_UART_WRITE_THRESHOLD 8


/*
 * led configuration
 *
 */

#define ALT_MODULE_CLASS_led altera_avalon_pio
#define LED_BASE 0x20000d0
#define LED_BIT_CLEARING_EDGE_REGISTER 0
#define LED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LED_CAPTURE 0
#define LED_DATA_WIDTH 9
#define LED_DO_TEST_BENCH_WIRING 0
#define LED_DRIVEN_SIM_VALUE 0
#define LED_EDGE_TYPE "NONE"
#define LED_FREQ 10000000
#define LED_HAS_IN 0
#define LED_HAS_OUT 1
#define LED_HAS_TRI 0
#define LED_IRQ -1
#define LED_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LED_IRQ_TYPE "NONE"
#define LED_NAME "/dev/led"
#define LED_RESET_VALUE 0
#define LED_SPAN 16
#define LED_TYPE "altera_avalon_pio"


/*
 * led configuration as viewed by dma_read_master
 *
 */

#define DMA_READ_MASTER_LED_BASE 0x20000d0
#define DMA_READ_MASTER_LED_BIT_CLEARING_EDGE_REGISTER 0
#define DMA_READ_MASTER_LED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DMA_READ_MASTER_LED_CAPTURE 0
#define DMA_READ_MASTER_LED_DATA_WIDTH 9
#define DMA_READ_MASTER_LED_DO_TEST_BENCH_WIRING 0
#define DMA_READ_MASTER_LED_DRIVEN_SIM_VALUE 0
#define DMA_READ_MASTER_LED_EDGE_TYPE "NONE"
#define DMA_READ_MASTER_LED_FREQ 10000000
#define DMA_READ_MASTER_LED_HAS_IN 0
#define DMA_READ_MASTER_LED_HAS_OUT 1
#define DMA_READ_MASTER_LED_HAS_TRI 0
#define DMA_READ_MASTER_LED_IRQ -1
#define DMA_READ_MASTER_LED_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_READ_MASTER_LED_IRQ_TYPE "NONE"
#define DMA_READ_MASTER_LED_NAME "/dev/led"
#define DMA_READ_MASTER_LED_RESET_VALUE 0
#define DMA_READ_MASTER_LED_SPAN 16
#define DMA_READ_MASTER_LED_TYPE "altera_avalon_pio"


/*
 * led configuration as viewed by dma_write_master
 *
 */

#define DMA_WRITE_MASTER_LED_BASE 0x20000d0
#define DMA_WRITE_MASTER_LED_BIT_CLEARING_EDGE_REGISTER 0
#define DMA_WRITE_MASTER_LED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DMA_WRITE_MASTER_LED_CAPTURE 0
#define DMA_WRITE_MASTER_LED_DATA_WIDTH 9
#define DMA_WRITE_MASTER_LED_DO_TEST_BENCH_WIRING 0
#define DMA_WRITE_MASTER_LED_DRIVEN_SIM_VALUE 0
#define DMA_WRITE_MASTER_LED_EDGE_TYPE "NONE"
#define DMA_WRITE_MASTER_LED_FREQ 10000000
#define DMA_WRITE_MASTER_LED_HAS_IN 0
#define DMA_WRITE_MASTER_LED_HAS_OUT 1
#define DMA_WRITE_MASTER_LED_HAS_TRI 0
#define DMA_WRITE_MASTER_LED_IRQ -1
#define DMA_WRITE_MASTER_LED_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_WRITE_MASTER_LED_IRQ_TYPE "NONE"
#define DMA_WRITE_MASTER_LED_NAME "/dev/led"
#define DMA_WRITE_MASTER_LED_RESET_VALUE 0
#define DMA_WRITE_MASTER_LED_SPAN 16
#define DMA_WRITE_MASTER_LED_TYPE "altera_avalon_pio"


/*
 * ltm_mm_if configuration
 *
 */

#define ALT_MODULE_CLASS_ltm_mm_if ltm_mm
#define LTM_MM_IF_BASE 0x801000
#define LTM_MM_IF_IRQ -1
#define LTM_MM_IF_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LTM_MM_IF_NAME "/dev/ltm_mm_if"
#define LTM_MM_IF_SPAN 64
#define LTM_MM_IF_TYPE "ltm_mm"


/*
 * sdram_ctrl configuration
 *
 */

#define ALT_MODULE_CLASS_sdram_ctrl altera_avalon_new_sdram_controller
#define SDRAM_CTRL_BASE 0x8000000
#define SDRAM_CTRL_CAS_LATENCY 3
#define SDRAM_CTRL_CONTENTS_INFO
#define SDRAM_CTRL_INIT_NOP_DELAY 0.0
#define SDRAM_CTRL_INIT_REFRESH_COMMANDS 2
#define SDRAM_CTRL_IRQ -1
#define SDRAM_CTRL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SDRAM_CTRL_IS_INITIALIZED 1
#define SDRAM_CTRL_NAME "/dev/sdram_ctrl"
#define SDRAM_CTRL_POWERUP_DELAY 200.0
#define SDRAM_CTRL_REFRESH_PERIOD 7.8125
#define SDRAM_CTRL_REGISTER_DATA_IN 1
#define SDRAM_CTRL_SDRAM_ADDR_WIDTH 0x18
#define SDRAM_CTRL_SDRAM_BANK_WIDTH 2
#define SDRAM_CTRL_SDRAM_COL_WIDTH 9
#define SDRAM_CTRL_SDRAM_DATA_WIDTH 32
#define SDRAM_CTRL_SDRAM_NUM_BANKS 4
#define SDRAM_CTRL_SDRAM_NUM_CHIPSELECTS 1
#define SDRAM_CTRL_SDRAM_ROW_WIDTH 13
#define SDRAM_CTRL_SHARED_DATA 0
#define SDRAM_CTRL_SIM_MODEL_BASE 0
#define SDRAM_CTRL_SPAN 67108864
#define SDRAM_CTRL_STARVATION_INDICATOR 0
#define SDRAM_CTRL_TRISTATE_BRIDGE_SLAVE ""
#define SDRAM_CTRL_TYPE "altera_avalon_new_sdram_controller"
#define SDRAM_CTRL_T_AC 5.5
#define SDRAM_CTRL_T_MRD 3
#define SDRAM_CTRL_T_RCD 20.0
#define SDRAM_CTRL_T_RFC 70.0
#define SDRAM_CTRL_T_RP 20.0
#define SDRAM_CTRL_T_WR 14.0


/*
 * sdram_ctrl configuration as viewed by dma_read_master
 *
 */

#define DMA_READ_MASTER_SDRAM_CTRL_BASE 0x8000000
#define DMA_READ_MASTER_SDRAM_CTRL_CAS_LATENCY 3
#define DMA_READ_MASTER_SDRAM_CTRL_CONTENTS_INFO
#define DMA_READ_MASTER_SDRAM_CTRL_INIT_NOP_DELAY 0.0
#define DMA_READ_MASTER_SDRAM_CTRL_INIT_REFRESH_COMMANDS 2
#define DMA_READ_MASTER_SDRAM_CTRL_IRQ -1
#define DMA_READ_MASTER_SDRAM_CTRL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_READ_MASTER_SDRAM_CTRL_IS_INITIALIZED 1
#define DMA_READ_MASTER_SDRAM_CTRL_NAME "/dev/sdram_ctrl"
#define DMA_READ_MASTER_SDRAM_CTRL_POWERUP_DELAY 200.0
#define DMA_READ_MASTER_SDRAM_CTRL_REFRESH_PERIOD 7.8125
#define DMA_READ_MASTER_SDRAM_CTRL_REGISTER_DATA_IN 1
#define DMA_READ_MASTER_SDRAM_CTRL_SDRAM_ADDR_WIDTH 0x18
#define DMA_READ_MASTER_SDRAM_CTRL_SDRAM_BANK_WIDTH 2
#define DMA_READ_MASTER_SDRAM_CTRL_SDRAM_COL_WIDTH 9
#define DMA_READ_MASTER_SDRAM_CTRL_SDRAM_DATA_WIDTH 32
#define DMA_READ_MASTER_SDRAM_CTRL_SDRAM_NUM_BANKS 4
#define DMA_READ_MASTER_SDRAM_CTRL_SDRAM_NUM_CHIPSELECTS 1
#define DMA_READ_MASTER_SDRAM_CTRL_SDRAM_ROW_WIDTH 13
#define DMA_READ_MASTER_SDRAM_CTRL_SHARED_DATA 0
#define DMA_READ_MASTER_SDRAM_CTRL_SIM_MODEL_BASE 0
#define DMA_READ_MASTER_SDRAM_CTRL_SPAN 67108864
#define DMA_READ_MASTER_SDRAM_CTRL_STARVATION_INDICATOR 0
#define DMA_READ_MASTER_SDRAM_CTRL_TRISTATE_BRIDGE_SLAVE ""
#define DMA_READ_MASTER_SDRAM_CTRL_TYPE "altera_avalon_new_sdram_controller"
#define DMA_READ_MASTER_SDRAM_CTRL_T_AC 5.5
#define DMA_READ_MASTER_SDRAM_CTRL_T_MRD 3
#define DMA_READ_MASTER_SDRAM_CTRL_T_RCD 20.0
#define DMA_READ_MASTER_SDRAM_CTRL_T_RFC 70.0
#define DMA_READ_MASTER_SDRAM_CTRL_T_RP 20.0
#define DMA_READ_MASTER_SDRAM_CTRL_T_WR 14.0


/*
 * sdram_ctrl configuration as viewed by dma_write_master
 *
 */

#define DMA_WRITE_MASTER_SDRAM_CTRL_BASE 0x8000000
#define DMA_WRITE_MASTER_SDRAM_CTRL_CAS_LATENCY 3
#define DMA_WRITE_MASTER_SDRAM_CTRL_CONTENTS_INFO
#define DMA_WRITE_MASTER_SDRAM_CTRL_INIT_NOP_DELAY 0.0
#define DMA_WRITE_MASTER_SDRAM_CTRL_INIT_REFRESH_COMMANDS 2
#define DMA_WRITE_MASTER_SDRAM_CTRL_IRQ -1
#define DMA_WRITE_MASTER_SDRAM_CTRL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_WRITE_MASTER_SDRAM_CTRL_IS_INITIALIZED 1
#define DMA_WRITE_MASTER_SDRAM_CTRL_NAME "/dev/sdram_ctrl"
#define DMA_WRITE_MASTER_SDRAM_CTRL_POWERUP_DELAY 200.0
#define DMA_WRITE_MASTER_SDRAM_CTRL_REFRESH_PERIOD 7.8125
#define DMA_WRITE_MASTER_SDRAM_CTRL_REGISTER_DATA_IN 1
#define DMA_WRITE_MASTER_SDRAM_CTRL_SDRAM_ADDR_WIDTH 0x18
#define DMA_WRITE_MASTER_SDRAM_CTRL_SDRAM_BANK_WIDTH 2
#define DMA_WRITE_MASTER_SDRAM_CTRL_SDRAM_COL_WIDTH 9
#define DMA_WRITE_MASTER_SDRAM_CTRL_SDRAM_DATA_WIDTH 32
#define DMA_WRITE_MASTER_SDRAM_CTRL_SDRAM_NUM_BANKS 4
#define DMA_WRITE_MASTER_SDRAM_CTRL_SDRAM_NUM_CHIPSELECTS 1
#define DMA_WRITE_MASTER_SDRAM_CTRL_SDRAM_ROW_WIDTH 13
#define DMA_WRITE_MASTER_SDRAM_CTRL_SHARED_DATA 0
#define DMA_WRITE_MASTER_SDRAM_CTRL_SIM_MODEL_BASE 0
#define DMA_WRITE_MASTER_SDRAM_CTRL_SPAN 67108864
#define DMA_WRITE_MASTER_SDRAM_CTRL_STARVATION_INDICATOR 0
#define DMA_WRITE_MASTER_SDRAM_CTRL_TRISTATE_BRIDGE_SLAVE ""
#define DMA_WRITE_MASTER_SDRAM_CTRL_TYPE "altera_avalon_new_sdram_controller"
#define DMA_WRITE_MASTER_SDRAM_CTRL_T_AC 5.5
#define DMA_WRITE_MASTER_SDRAM_CTRL_T_MRD 3
#define DMA_WRITE_MASTER_SDRAM_CTRL_T_RCD 20.0
#define DMA_WRITE_MASTER_SDRAM_CTRL_T_RFC 70.0
#define DMA_WRITE_MASTER_SDRAM_CTRL_T_RP 20.0
#define DMA_WRITE_MASTER_SDRAM_CTRL_T_WR 14.0


/*
 * syspll configuration
 *
 */

#define ALT_MODULE_CLASS_syspll altpll
#define SYSPLL_BASE 0x801090
#define SYSPLL_IRQ -1
#define SYSPLL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYSPLL_NAME "/dev/syspll"
#define SYSPLL_SPAN 16
#define SYSPLL_TYPE "altpll"


/*
 * timer configuration
 *
 */

#define ALT_MODULE_CLASS_timer altera_avalon_timer
#define TIMER_ALWAYS_RUN 0
#define TIMER_BASE 0x2000020
#define TIMER_COUNTER_SIZE 32
#define TIMER_FIXED_PERIOD 0
#define TIMER_FREQ 10000000
#define TIMER_IRQ 1
#define TIMER_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMER_LOAD_VALUE 9
#define TIMER_MULT 1.0E-6
#define TIMER_NAME "/dev/timer"
#define TIMER_PERIOD 1
#define TIMER_PERIOD_UNITS "us"
#define TIMER_RESET_OUTPUT 0
#define TIMER_SNAPSHOT 1
#define TIMER_SPAN 32
#define TIMER_TICKS_PER_SEC 1000000.0
#define TIMER_TIMEOUT_PULSE_OUTPUT 0
#define TIMER_TYPE "altera_avalon_timer"


/*
 * timer configuration as viewed by dma_read_master
 *
 */

#define DMA_READ_MASTER_TIMER_ALWAYS_RUN 0
#define DMA_READ_MASTER_TIMER_BASE 0x2000020
#define DMA_READ_MASTER_TIMER_COUNTER_SIZE 32
#define DMA_READ_MASTER_TIMER_FIXED_PERIOD 0
#define DMA_READ_MASTER_TIMER_FREQ 10000000
#define DMA_READ_MASTER_TIMER_IRQ -1
#define DMA_READ_MASTER_TIMER_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_READ_MASTER_TIMER_LOAD_VALUE 9
#define DMA_READ_MASTER_TIMER_MULT 1.0E-6
#define DMA_READ_MASTER_TIMER_NAME "/dev/timer"
#define DMA_READ_MASTER_TIMER_PERIOD 1
#define DMA_READ_MASTER_TIMER_PERIOD_UNITS "us"
#define DMA_READ_MASTER_TIMER_RESET_OUTPUT 0
#define DMA_READ_MASTER_TIMER_SNAPSHOT 1
#define DMA_READ_MASTER_TIMER_SPAN 32
#define DMA_READ_MASTER_TIMER_TICKS_PER_SEC 1000000.0
#define DMA_READ_MASTER_TIMER_TIMEOUT_PULSE_OUTPUT 0
#define DMA_READ_MASTER_TIMER_TYPE "altera_avalon_timer"


/*
 * timer configuration as viewed by dma_write_master
 *
 */

#define DMA_WRITE_MASTER_TIMER_ALWAYS_RUN 0
#define DMA_WRITE_MASTER_TIMER_BASE 0x2000020
#define DMA_WRITE_MASTER_TIMER_COUNTER_SIZE 32
#define DMA_WRITE_MASTER_TIMER_FIXED_PERIOD 0
#define DMA_WRITE_MASTER_TIMER_FREQ 10000000
#define DMA_WRITE_MASTER_TIMER_IRQ -1
#define DMA_WRITE_MASTER_TIMER_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_WRITE_MASTER_TIMER_LOAD_VALUE 9
#define DMA_WRITE_MASTER_TIMER_MULT 1.0E-6
#define DMA_WRITE_MASTER_TIMER_NAME "/dev/timer"
#define DMA_WRITE_MASTER_TIMER_PERIOD 1
#define DMA_WRITE_MASTER_TIMER_PERIOD_UNITS "us"
#define DMA_WRITE_MASTER_TIMER_RESET_OUTPUT 0
#define DMA_WRITE_MASTER_TIMER_SNAPSHOT 1
#define DMA_WRITE_MASTER_TIMER_SPAN 32
#define DMA_WRITE_MASTER_TIMER_TICKS_PER_SEC 1000000.0
#define DMA_WRITE_MASTER_TIMER_TIMEOUT_PULSE_OUTPUT 0
#define DMA_WRITE_MASTER_TIMER_TYPE "altera_avalon_timer"


/*
 * touchirq configuration
 *
 */

#define ALT_MODULE_CLASS_touchirq altera_avalon_pio
#define TOUCHIRQ_BASE 0x801060
#define TOUCHIRQ_BIT_CLEARING_EDGE_REGISTER 0
#define TOUCHIRQ_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TOUCHIRQ_CAPTURE 1
#define TOUCHIRQ_DATA_WIDTH 1
#define TOUCHIRQ_DO_TEST_BENCH_WIRING 1
#define TOUCHIRQ_DRIVEN_SIM_VALUE 0
#define TOUCHIRQ_EDGE_TYPE "RISING"
#define TOUCHIRQ_FREQ 150000000
#define TOUCHIRQ_HAS_IN 1
#define TOUCHIRQ_HAS_OUT 0
#define TOUCHIRQ_HAS_TRI 0
#define TOUCHIRQ_IRQ 4
#define TOUCHIRQ_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TOUCHIRQ_IRQ_TYPE "EDGE"
#define TOUCHIRQ_NAME "/dev/touchirq"
#define TOUCHIRQ_RESET_VALUE 0
#define TOUCHIRQ_SPAN 16
#define TOUCHIRQ_TYPE "altera_avalon_pio"


/*
 * touchx configuration
 *
 */

#define ALT_MODULE_CLASS_touchx altera_avalon_pio
#define TOUCHX_BASE 0x801080
#define TOUCHX_BIT_CLEARING_EDGE_REGISTER 0
#define TOUCHX_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TOUCHX_CAPTURE 0
#define TOUCHX_DATA_WIDTH 12
#define TOUCHX_DO_TEST_BENCH_WIRING 1
#define TOUCHX_DRIVEN_SIM_VALUE 0
#define TOUCHX_EDGE_TYPE "NONE"
#define TOUCHX_FREQ 150000000
#define TOUCHX_HAS_IN 1
#define TOUCHX_HAS_OUT 0
#define TOUCHX_HAS_TRI 0
#define TOUCHX_IRQ -1
#define TOUCHX_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TOUCHX_IRQ_TYPE "NONE"
#define TOUCHX_NAME "/dev/touchx"
#define TOUCHX_RESET_VALUE 0
#define TOUCHX_SPAN 16
#define TOUCHX_TYPE "altera_avalon_pio"


/*
 * touchy configuration
 *
 */

#define ALT_MODULE_CLASS_touchy altera_avalon_pio
#define TOUCHY_BASE 0x801070
#define TOUCHY_BIT_CLEARING_EDGE_REGISTER 0
#define TOUCHY_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TOUCHY_CAPTURE 0
#define TOUCHY_DATA_WIDTH 12
#define TOUCHY_DO_TEST_BENCH_WIRING 1
#define TOUCHY_DRIVEN_SIM_VALUE 0
#define TOUCHY_EDGE_TYPE "NONE"
#define TOUCHY_FREQ 150000000
#define TOUCHY_HAS_IN 1
#define TOUCHY_HAS_OUT 0
#define TOUCHY_HAS_TRI 0
#define TOUCHY_IRQ -1
#define TOUCHY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TOUCHY_IRQ_TYPE "NONE"
#define TOUCHY_NAME "/dev/touchy"
#define TOUCHY_RESET_VALUE 0
#define TOUCHY_SPAN 16
#define TOUCHY_TYPE "altera_avalon_pio"


/*
 * uart0 configuration
 *
 */

#define ALT_MODULE_CLASS_uart0 altera_avalon_uart
#define UART0_BASE 0x2000000
#define UART0_BAUD 115200
#define UART0_DATA_BITS 8
#define UART0_FIXED_BAUD 1
#define UART0_FREQ 10000000
#define UART0_IRQ 2
#define UART0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define UART0_NAME "/dev/uart0"
#define UART0_PARITY 'N'
#define UART0_SIM_CHAR_STREAM ""
#define UART0_SIM_TRUE_BAUD 0
#define UART0_SPAN 32
#define UART0_STOP_BITS 1
#define UART0_SYNC_REG_DEPTH 2
#define UART0_TYPE "altera_avalon_uart"
#define UART0_USE_CTS_RTS 0
#define UART0_USE_EOP_REGISTER 0


/*
 * uart0 configuration as viewed by dma_read_master
 *
 */

#define DMA_READ_MASTER_UART0_BASE 0x2000000
#define DMA_READ_MASTER_UART0_BAUD 115200
#define DMA_READ_MASTER_UART0_DATA_BITS 8
#define DMA_READ_MASTER_UART0_FIXED_BAUD 1
#define DMA_READ_MASTER_UART0_FREQ 10000000
#define DMA_READ_MASTER_UART0_IRQ -1
#define DMA_READ_MASTER_UART0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_READ_MASTER_UART0_NAME "/dev/uart0"
#define DMA_READ_MASTER_UART0_PARITY 'N'
#define DMA_READ_MASTER_UART0_SIM_CHAR_STREAM ""
#define DMA_READ_MASTER_UART0_SIM_TRUE_BAUD 0
#define DMA_READ_MASTER_UART0_SPAN 32
#define DMA_READ_MASTER_UART0_STOP_BITS 1
#define DMA_READ_MASTER_UART0_SYNC_REG_DEPTH 2
#define DMA_READ_MASTER_UART0_TYPE "altera_avalon_uart"
#define DMA_READ_MASTER_UART0_USE_CTS_RTS 0
#define DMA_READ_MASTER_UART0_USE_EOP_REGISTER 0


/*
 * uart0 configuration as viewed by dma_write_master
 *
 */

#define DMA_WRITE_MASTER_UART0_BASE 0x2000000
#define DMA_WRITE_MASTER_UART0_BAUD 115200
#define DMA_WRITE_MASTER_UART0_DATA_BITS 8
#define DMA_WRITE_MASTER_UART0_FIXED_BAUD 1
#define DMA_WRITE_MASTER_UART0_FREQ 10000000
#define DMA_WRITE_MASTER_UART0_IRQ -1
#define DMA_WRITE_MASTER_UART0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_WRITE_MASTER_UART0_NAME "/dev/uart0"
#define DMA_WRITE_MASTER_UART0_PARITY 'N'
#define DMA_WRITE_MASTER_UART0_SIM_CHAR_STREAM ""
#define DMA_WRITE_MASTER_UART0_SIM_TRUE_BAUD 0
#define DMA_WRITE_MASTER_UART0_SPAN 32
#define DMA_WRITE_MASTER_UART0_STOP_BITS 1
#define DMA_WRITE_MASTER_UART0_SYNC_REG_DEPTH 2
#define DMA_WRITE_MASTER_UART0_TYPE "altera_avalon_uart"
#define DMA_WRITE_MASTER_UART0_USE_CTS_RTS 0
#define DMA_WRITE_MASTER_UART0_USE_EOP_REGISTER 0

#endif /* __SYSTEM_H_ */
